---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    #getting password and username from ansible vault
    git_repo_url: https://{{ git_username | urlencode }}:{{ git_password | urlencode }}@github.com/aratrika1996/BCDV-4033-Lab1.git
    repo_path: /home/repo
    repo_branch: main
  vars_files:
    - gitsecrets.yml
  tasks: 
  - name: Install sudo
    apt:
      name: sudo
      state: present

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
     update_cache: yes
     
  - name: Ansible shell module multiple commands
    shell: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'

  - name: Install reqired packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - curl
      - wget
      - nginx
      - nodejs

  - name: Copy SSH key to remote node
    copy:
      src: /root/.ssh/id_rsa
      dest: /root/.ssh/id_rsa
      owner: root
      group: root
      mode: '0600'


  - name: Clone a private repository
    git:
      repo: "{{ git_repo_url }}"
      dest: "{{ repo_path }}"
      version: "{{ repo_branch }}"
      accept_hostkey: yes
      update: yes
      clone: yes
    environment:
      GIT_TERMINAL_PROMPT: "0"

  - name: Install packages based on package.json using the npm
    npm:
      path: "{{ repo_path }}"
      state: present

  - name: Build app
    command: npm run build
    args:
      chdir: "{{ repo_path }}"